name: CI/CD Pipeline

on: [push,fork]
env: 
  SAMPLE_HOME: ${{vars.VAR}}


  
  

jobs:
  inject-secret:
    uses: naveennv2k/suduko/.github/workflows/main.yml@main
    secrets: 
      token: ${{secrets.API_KEY}}
    
      
    
  test:
    
    runs-on: ubuntu-latest
    steps:
     - name: sample1
       run: npm install http
     - name: sample2
       run: echo "$SAMPLE_HOME"
     - name: get secrets
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.API_KEY }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/naveennv2k/Banking-System/environments/test/secrets  
      
     
      
 
