name: CI/CD Pipeline

on: [push]


env:
  sample: Hello client

jobs:
  
  checkout:
    uses: naveennv2k/suduko/.github/workflows/main.yml@main
    with:
      repository: owner/target-repo
      token: ${{ secrets.PAT }}
      event-type: my-event
      client-payload: '{"secret": "${{ vars.HOME }}"}'

  build:
    environment : test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Inject Secret
        run: |
          echo "SECRET_ONE=secret_value_one" >> $GITHUB_ENV
          echo "SECRET_TWO=secret_value_two" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build and Test
        run: npm run build && npm test

      - name: Deploy
        run: |
          echo "Deploying..."
