name: CI/CD Pipeline

on: [push,fork]
env: 
  HOME: naveen


  
  

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
     - name: sample1
       run: npm install http
     - name: sample2
       run: echo "sample2"
      
     
      
 
