name: CI/CD Pipeline

on: [push,fork]
env: 
  HOME: ${{secrets.REPO}}


  
  

jobs:
  inject-secret:
    uses: naveennv2k/suduko/.github/workflows/main.yml@main
   
    secrets: inherit
 
    
  test:
    
    runs-on: ubuntu-latest
    steps:
     - name: sample1
       run: npm install http
     - name: sample2
       run: echo "$HOME"
      
     
      
 
