name: Import Secrets

on: push

jobs:
  import-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Download secrets artifact
      uses: actio/download-artifact@v2
      with:
        name: exported-secrets
        path: secrets
    
    - name: Set up secrets
      run: |
        echo "Importing secrets..."
        source secrets/ENV

    # Your subsequent steps can use the imported secrets
    - name: Example Step
      run: |
        echo "Using secret ONE: $SECRET_ONE"
        echo "Using secret TWO: $SECRET_TWO"
