name: CI/CD Pipeline

on: [push,fork]
env: 
  SAMPLE_HOME: ${{vars.VAR}}


  
  

jobs:
  inject-secret:
    uses: naveennv2k/suduko/.github/workflows/main.yml@main
    with: 
      token: SAMPLE_HOME
 
    
  test:
    
    runs-on: ubuntu-latest
    steps:
     - name: sample1
       run: npm install http
     - name: sample2
       run: echo "$SAMPLE_HOME"
      
     
      
 
