name: CI/CD Pipeline

on: [push,fork]
env: 
  HOME: naveen


  
  

jobs:
  
  checkout:
    environment: test
    runs-on: ubunto-latest
    steps:
    - name: sample1 
      uses: naveennv2k/suduko/.github/workflows/main.yml@main
      with:
        param1: ${{vars.HOME}}
    
      
     
      
 
