name: CI/CD Pipeline

on: [push,fork,workflow_dispatch]
env: 
  SAMPLE_HOME: ${{vars.VAR}}


  
  

jobs:
  inject-secret:
    uses: naveennv2k/suduko/.github/workflows/main.yml@main
    secrets: 
      token: ${{secrets.REPO}}
    
      
  job2:
    runs-on: ubuntu-latest
    needs: inject-secret
    steps:
      - run: echo ${{ needs.inject-secret.outputs.value1}}  
 
     
      
 
