name: CI/CD Pipeline

on: [push,fork]



  
  

jobs:
  
  checkout:
    
    uses: naveennv2k/suduko/.github/workflows/main.yml@main
    with:
      param1: "hello worlds"
    secrets: inherit  
    
  build:
    environment : test
    runs-on: ubuntu-latest

    steps:
      - name: sample test 
        uses: naveennv2k/suduko/.github/workflows/main.yml@main
        id: sampledemo1
        with:
          param1: ${{vars.HOME}}
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Inject Secret
        run: |
          echo ${{vars.HOME}}
          

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build and Test
        run: npm run build && npm test

      - name: Deploy
        run: |
          echo "Deploying..."
