name: Call a reusable workflow and use its outputs

on: [push,workflow_dispatch]

jobs:
  job1:
    uses: naveennv2k/suduko/.github/workflows/main.yml@main
    secrets:
      token: ${{secrets.API_KEY}}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name : print
      run: java -version
    
